CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);

BEGIN TRANSACTION;

CREATE TABLE "QRTZ_CALENDARS" (
    "SCHED_NAME" TEXT NOT NULL,
    "CALENDAR_NAME" TEXT NOT NULL,
    "CALENDAR" BLOB NOT NULL,
    CONSTRAINT "PK_QRTZ_CALENDARS" PRIMARY KEY ("SCHED_NAME", "CALENDAR_NAME")
);

CREATE TABLE "QRTZ_FIRED_TRIGGERS" (
    "SCHED_NAME" TEXT NOT NULL,
    "ENTRY_ID" TEXT NOT NULL,
    "TRIGGER_NAME" TEXT NOT NULL,
    "TRIGGER_GROUP" TEXT NOT NULL,
    "INSTANCE_NAME" TEXT NOT NULL,
    "FIRED_TIME" INTEGER NOT NULL,
    "SCHED_TIME" INTEGER NOT NULL,
    "PRIORITY" INTEGER NOT NULL,
    "STATE" TEXT NOT NULL,
    "JOB_NAME" TEXT NULL,
    "JOB_GROUP" TEXT NULL,
    "IS_NONCONCURRENT" INTEGER NULL,
    "REQUESTS_RECOVERY" INTEGER NULL,
    CONSTRAINT "PK_QRTZ_FIRED_TRIGGERS" PRIMARY KEY ("SCHED_NAME", "ENTRY_ID")
);

CREATE TABLE "QRTZ_JOB_DETAILS" (
    "SCHED_NAME" TEXT NOT NULL,
    "JOB_NAME" TEXT NOT NULL,
    "JOB_GROUP" TEXT NOT NULL,
    "DESCRIPTION" TEXT NULL,
    "JOB_CLASS_NAME" TEXT NOT NULL,
    "IS_DURABLE" INTEGER NOT NULL,
    "IS_NONCONCURRENT" INTEGER NOT NULL,
    "IS_UPDATE_DATA" INTEGER NOT NULL,
    "REQUESTS_RECOVERY" INTEGER NOT NULL,
    "JOB_DATA" BLOB NULL,
    CONSTRAINT "PK_QRTZ_JOB_DETAILS" PRIMARY KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP")
);

CREATE TABLE "QRTZ_LOCKS" (
    "SCHED_NAME" TEXT NOT NULL,
    "LOCK_NAME" TEXT NOT NULL,
    CONSTRAINT "PK_QRTZ_LOCKS" PRIMARY KEY ("SCHED_NAME", "LOCK_NAME")
);

CREATE TABLE "QRTZ_PAUSED_TRIGGER_GRPS" (
    "SCHED_NAME" TEXT NOT NULL,
    "TRIGGER_GROUP" TEXT NOT NULL,
    CONSTRAINT "PK_QRTZ_PAUSED_TRIGGER_GRPS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_GROUP")
);

CREATE TABLE "QRTZ_SCHEDULER_STATE" (
    "SCHED_NAME" TEXT NOT NULL,
    "INSTANCE_NAME" TEXT NOT NULL,
    "LAST_CHECKIN_TIME" INTEGER NOT NULL,
    "CHECKIN_INTERVAL" INTEGER NOT NULL,
    CONSTRAINT "PK_QRTZ_SCHEDULER_STATE" PRIMARY KEY ("SCHED_NAME", "INSTANCE_NAME")
);

CREATE TABLE "QRTZ_TRIGGERS" (
    "SCHED_NAME" TEXT NOT NULL,
    "TRIGGER_NAME" TEXT NOT NULL,
    "TRIGGER_GROUP" TEXT NOT NULL,
    "JOB_NAME" TEXT NOT NULL,
    "JOB_GROUP" TEXT NOT NULL,
    "DESCRIPTION" TEXT NULL,
    "NEXT_FIRE_TIME" INTEGER NULL,
    "PREV_FIRE_TIME" INTEGER NULL,
    "PRIORITY" INTEGER NULL,
    "TRIGGER_STATE" TEXT NOT NULL,
    "TRIGGER_TYPE" TEXT NOT NULL,
    "START_TIME" INTEGER NOT NULL,
    "END_TIME" INTEGER NULL,
    "CALENDAR_NAME" TEXT NULL,
    "MISFIRE_INSTR" INTEGER NULL,
    "JOB_DATA" BLOB NULL,
    CONSTRAINT "PK_QRTZ_TRIGGERS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
    CONSTRAINT "FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS_SCHED_NAME_JOB_NAME_JOB_GROUP" FOREIGN KEY ("SCHED_NAME", "JOB_NAME", "JOB_GROUP") REFERENCES "QRTZ_JOB_DETAILS" ("SCHED_NAME", "JOB_NAME", "JOB_GROUP") ON DELETE CASCADE
);

CREATE TABLE "QRTZ_BLOB_TRIGGERS" (
    "SCHED_NAME" TEXT NOT NULL,
    "TRIGGER_NAME" TEXT NOT NULL,
    "TRIGGER_GROUP" TEXT NOT NULL,
    "BLOB_DATA" BLOB NULL,
    CONSTRAINT "PK_QRTZ_BLOB_TRIGGERS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
    CONSTRAINT "FK_QRTZ_BLOB_TRIGGERS_QRTZ_TRIGGERS_SCHED_NAME_TRIGGER_NAME_TRIGGER_GROUP" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") ON DELETE CASCADE
);

CREATE TABLE "QRTZ_CRON_TRIGGERS" (
    "SCHED_NAME" TEXT NOT NULL,
    "TRIGGER_NAME" TEXT NOT NULL,
    "TRIGGER_GROUP" TEXT NOT NULL,
    "CRON_EXPRESSION" TEXT NOT NULL,
    "TIME_ZONE_ID" TEXT NULL,
    CONSTRAINT "PK_QRTZ_CRON_TRIGGERS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
    CONSTRAINT "FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS_SCHED_NAME_TRIGGER_NAME_TRIGGER_GROUP" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") ON DELETE CASCADE
);

CREATE TABLE "QRTZ_SIMPLE_TRIGGERS" (
    "SCHED_NAME" TEXT NOT NULL,
    "TRIGGER_NAME" TEXT NOT NULL,
    "TRIGGER_GROUP" TEXT NOT NULL,
    "REPEAT_COUNT" INTEGER NOT NULL,
    "REPEAT_INTERVAL" INTEGER NOT NULL,
    "TIMES_TRIGGERED" INTEGER NOT NULL,
    CONSTRAINT "PK_QRTZ_SIMPLE_TRIGGERS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
    CONSTRAINT "FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS_SCHED_NAME_TRIGGER_NAME_TRIGGER_GROUP" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") ON DELETE CASCADE
);

CREATE TABLE "QRTZ_SIMPROP_TIGGERS" (
    "SCHED_NAME" TEXT NOT NULL,
    "TRIGGER_NAME" TEXT NOT NULL,
    "TRIGGER_GROUP" TEXT NOT NULL,
    "STR_PROP_1" TEXT NULL,
    "STR_PROP_2" TEXT NULL,
    "STR_PROP_3" TEXT NULL,
    "INT_PROP_1" INTEGER NULL,
    "INT_PROP_2" INTEGER NULL,
    "LONG_PROP_1" INTEGER NULL,
    "LONG_PROP_2" INTEGER NULL,
    "DEC_PROP_1" TEXT NULL,
    "DEC_PROP_2" TEXT NULL,
    "BOOL_PROP_1" INTEGER NULL,
    "BOOL_PROP_2" INTEGER NULL,
    "TIME_ZONE_ID" TEXT NULL,
    CONSTRAINT "PK_QRTZ_SIMPROP_TIGGERS" PRIMARY KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP"),
    CONSTRAINT "FK_QRTZ_SIMPROP_TIGGERS_QRTZ_TRIGGERS_SCHED_NAME_TRIGGER_NAME_TRIGGER_GROUP" FOREIGN KEY ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") REFERENCES "QRTZ_TRIGGERS" ("SCHED_NAME", "TRIGGER_NAME", "TRIGGER_GROUP") ON DELETE CASCADE
);

CREATE INDEX "IX_QRTZ_TRIGGERS_SCHED_NAME_JOB_NAME_JOB_GROUP" ON "QRTZ_TRIGGERS" ("SCHED_NAME", "JOB_NAME", "JOB_GROUP");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210727151039_InitMigration', '5.0.8');

COMMIT;

